name_space: alpha_rise
poses_source: odometry/filtered/local
geo_pose_source: odometry/geopose
vitals_source: power
waypoint_topic: path3d/update_geo_path

get_state_service: helm/get_state
change_state_service: helm/change_state

get_waypoints_service: helm/path_3d/get_next_waypoints
get_states_service: helm/get_states
power_items: [power_manager/jetson, power_manager/24v, power_manager/lumen]